//created on: 2015.04.22.
package rules

import util.Message;
import nodes.*;
//list any import classes here.



//declare any global variables here




rule "Rule 1 : JOIN"

    when
    	$endBIN : Message ($senderBIN: sender, type == Message.TYPE_PROCESSING_END, $tsBIN : timestamp, $idBIN : id)
    		eval ($senderBIN == BillingInfoNode.class)

    	$endPRN : Message ($senderPRN: sender, type == Message.TYPE_PROCESSING_END, $tsPRN : timestamp, $idPRN : id)
    		eval ($senderPRN == ProcessReservationNode.class)
    	
    	eval ($idBIN == $idPRN)
    	eval (Math.abs($tsBIN - $tsPRN) > 5000)
    then
		System.out.println("Slow join!!!!");
end